export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as HowItWorks } from './HowItWorks'
export { default as ForWho } from './ForWho'
export { default as AppScreenshots } from './AppScreenshots'
export { default as Benefits } from './Benefits'
export { default as Testimonials } from './Testimonials'
export { default as DownloadCTA } from './DownloadCTA'
